### PR TITLE
Allow for JDK configure arguments via EXTRA_FLAGS and for DEBUG_BINARIES...

### PR DESCRIPTION
**Pull request by andcoope**
... to be settable

### CODE REVIEW

**Comment by hgomez** [comment]
Could you rename flag from EXTRA_FLAGS to XEXTRA_FLAGS ?
All external parameters are prefixed by X in Obuildfactory.

Thanks

**Comment by andcoope** [comment]
Sure - just renamed it.

**Comment by hgomez** [comment]
Good.

Why did there is 

CONT=$BUILD_PROFILE make DEBUG_BINARIES=$DEBUG_BINARIES EXTRA_CFLAGS=$EXTRA_CFLAGS images

**Comment by andcoope** [comment]
That line was already there, and was DEBUG_BINARIES=true, which meant that the binaries ALWAYS have debug information in them regardless of settings. That implies a JDK/JRE build of 160Mb. I simply fixed that to pass the actual value of DEBUG_BINARIES in as opposed to always forcing it to true.

**Comment by hgomez** [comment]
I should have a look on DEBUG_BINARIES=$DEBUG_BINARIES

**Comment by hgomez** [comment]
Merging it for now, I'll update DEBUG_BINARIES then

**Comment by hgomez** [comment]
DEBUG_BINARIES was a trick and should be kept 

see https://github.com/hgomez/obuildfactory/commit/163c11e3539fb94f6b11f87bed4dc3167b5b0489

**Comment by andcoope** [comment]
Hmm - the presence of the environment variable, or the fact you'd forced it to true? I can build successfully with the latest gcc with DEBUG_BINARIES set to false. If it's just the presence of the environment variable, then that should work too.

**Comment by hgomez** [comment]
Yep, I'm unsure why it's here, I had to dig in openjdk make file and mailing lists to find this one

**Comment by andcoope** [comment]
Definitely looks odd. How about this - create an XDEBUG_BINARIES that, if set, overrides the DEBUG_BINARIES that is set to true otherwise? That way we can override it for those of us who want to compile without debug symbols.

**Comment by hgomez** [comment]
Good idea. Send a PR for this one.
We should take care to not have more build flags than ... openjdk by itself :)

**Comment by andcoope** [comment]
Done. New PR submitted.

**Pull request merged**
